In [40]:
import numpy as np

In [41]:
#No.1
array1D = np.arange(10)
print(array1D)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
#No.2
boolean_arr = np.ones((3,3), dtype= bool)
print(boolean_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [43]:
#No.3
arr_1 = np.arange(1,11)
print("Array =", arr_1)
arr1 = np.arange(1,11,2)
print("Odd Numbers from array =",(arr1))

Array = [ 1  2  3  4  5  6  7  8  9 10]
Odd Numbers from array = [1 3 5 7 9]


In [44]:
#No.4
arr_1 = np.arange(1,11)
print("Array =", arr_1)
odd_no = ((arr_1 % 2) == 1)
arr_1[odd_no] = -1
print(arr_1)

Array = [ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [54]:
#No.5
arr2D = np.arange(1,5).reshape(2,2,)
print("2D Array =", arr2D)

2D Array = [[1 2]
 [3 4]]


In [57]:
#No.6
a = np.arange(5,14).reshape(3,3)
b = np.arange(14,23).reshape(3,3)
c = np.dot(a,b)
print("a =", a)
print("b =", b)
print("c =", c)

total_sum = np.sum(c)
print("Total sum =", total_sum)


a = [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
b = [[14 15 16]
 [17 18 19]
 [20 21 22]]
c = [[312 330 348]
 [465 492 519]
 [618 654 690]]
Total sum = 4428


In [68]:
#Extension no.1 

array1 = np.array([1, 2, 3])
print(array1)
repeat = np.repeat(array1, 3)
usingtile = np.tile(array1, 3)
np.r_[repeat, usingtile]

[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [69]:
#Extension no.2 

a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8, 9])
np.setdiff1d(a,b)

array([1, 2, 3])

In [84]:
#Extension no.3

arr_3 = np.where((a>=3) & (a<7))
arr3 = a[arr_3]
print(arr3)
arr_4 = np.where((b>=3) & (b<7))
arr4 = b[arr_4]
print(arr4)
arr5 = np.dot(arr4,arr3)

tsum = np.sum(arr5)
print("Total sum =", tsum)

[3 4 5]
[4 5 6]
Total sum = 62
